id = "zed-lambdapi"
name = "LambdaPi"
version = "0.0.1"
schema_version = 1
authors = ["Ciarán Dunne <cciaranddunne@gmail.com>"]
description = "Support for LambdaPi in Zed"
repository = "https://github.com/ciaran-matthew-dunne/zed-lambdapi"

[grammars.lambdapi]
repository = "https://github.com/ciaran-matthew-dunne/tree-sitter-lambdapi"
rev = "8ba546b520c8773039aec3a8819b59f5dd268e52"

[language_servers.lambdapi-lsp]
name = "lambdapi-lsp"
languages = ["LambdaPi"]
